language: en
pipeline: pretrained_embeddings_spacy
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy

#language: "en_core_web_sm"
#
#pipeline:
#- name: "nlp_spacy"
#- name: "tokenizer_whitespace"
#- name: "intent_entity_featurizer_regex"
#- name: "ner_crf"
#- name: "ner_synonyms"
#- name: "intent_featurizer_count_vectors"
#- name: "intent_classifier_tensorflow_embedding"
#  intent_tokenization_flag: true
#  intent_split_symbol: "+"